// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/health_check/health_check.proto

package health_check

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_health_check_health_check_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_health_check_health_check_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_health_check_health_check_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Massage       string                 `protobuf:"bytes,1,opt,name=massage,proto3" json:"massage,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_health_check_health_check_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_health_check_health_check_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_health_check_health_check_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetMassage() string {
	if x != nil {
		return x.Massage
	}
	return ""
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_proto_health_check_health_check_proto protoreflect.FileDescriptor

const file_proto_health_check_health_check_proto_rawDesc = "" +
	"\n" +
	"%proto/health_check/health_check.proto\x12\fhealth_check\"\x0f\n" +
	"\rHealthRequest\"p\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\amassage\x18\x01 \x01(\tR\amassage\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion2^\n" +
	"\x12HealthCheckHandler\x12H\n" +
	"\vHealthCheck\x12\x1b.health_check.HealthRequest\x1a\x1c.health_check.HealthResponseB>Z<github.com/madevara24/go-grpc-boilerplate/proto/health_checkb\x06proto3"

var (
	file_proto_health_check_health_check_proto_rawDescOnce sync.Once
	file_proto_health_check_health_check_proto_rawDescData []byte
)

func file_proto_health_check_health_check_proto_rawDescGZIP() []byte {
	file_proto_health_check_health_check_proto_rawDescOnce.Do(func() {
		file_proto_health_check_health_check_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_health_check_health_check_proto_rawDesc), len(file_proto_health_check_health_check_proto_rawDesc)))
	})
	return file_proto_health_check_health_check_proto_rawDescData
}

var file_proto_health_check_health_check_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_health_check_health_check_proto_goTypes = []any{
	(*HealthRequest)(nil),  // 0: health_check.HealthRequest
	(*HealthResponse)(nil), // 1: health_check.HealthResponse
}
var file_proto_health_check_health_check_proto_depIdxs = []int32{
	0, // 0: health_check.HealthCheckHandler.HealthCheck:input_type -> health_check.HealthRequest
	1, // 1: health_check.HealthCheckHandler.HealthCheck:output_type -> health_check.HealthResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_health_check_health_check_proto_init() }
func file_proto_health_check_health_check_proto_init() {
	if File_proto_health_check_health_check_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_health_check_health_check_proto_rawDesc), len(file_proto_health_check_health_check_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_health_check_health_check_proto_goTypes,
		DependencyIndexes: file_proto_health_check_health_check_proto_depIdxs,
		MessageInfos:      file_proto_health_check_health_check_proto_msgTypes,
	}.Build()
	File_proto_health_check_health_check_proto = out.File
	file_proto_health_check_health_check_proto_goTypes = nil
	file_proto_health_check_health_check_proto_depIdxs = nil
}
