// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/health_check/health_check.proto

package health_check

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HealthCheckHandler_HealthCheck_FullMethodName = "/health_check.HealthCheckHandler/HealthCheck"
)

// HealthCheckHandlerClient is the client API for HealthCheckHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HealthCheckHandlerClient interface {
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type healthCheckHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthCheckHandlerClient(cc grpc.ClientConnInterface) HealthCheckHandlerClient {
	return &healthCheckHandlerClient{cc}
}

func (c *healthCheckHandlerClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, HealthCheckHandler_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthCheckHandlerServer is the server API for HealthCheckHandler service.
// All implementations must embed UnimplementedHealthCheckHandlerServer
// for forward compatibility.
type HealthCheckHandlerServer interface {
	HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedHealthCheckHandlerServer()
}

// UnimplementedHealthCheckHandlerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHealthCheckHandlerServer struct{}

func (UnimplementedHealthCheckHandlerServer) HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedHealthCheckHandlerServer) mustEmbedUnimplementedHealthCheckHandlerServer() {}
func (UnimplementedHealthCheckHandlerServer) testEmbeddedByValue()                            {}

// UnsafeHealthCheckHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthCheckHandlerServer will
// result in compilation errors.
type UnsafeHealthCheckHandlerServer interface {
	mustEmbedUnimplementedHealthCheckHandlerServer()
}

func RegisterHealthCheckHandlerServer(s grpc.ServiceRegistrar, srv HealthCheckHandlerServer) {
	// If the following call pancis, it indicates UnimplementedHealthCheckHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HealthCheckHandler_ServiceDesc, srv)
}

func _HealthCheckHandler_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthCheckHandlerServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthCheckHandler_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthCheckHandlerServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HealthCheckHandler_ServiceDesc is the grpc.ServiceDesc for HealthCheckHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthCheckHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "health_check.HealthCheckHandler",
	HandlerType: (*HealthCheckHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _HealthCheckHandler_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/health_check/health_check.proto",
}
